INSERT INTO day VALUES("2021.06.12");
INSERT INTO day VALUES("2021.06.13");
INSERT INTO day VALUES("2021.06.14");
INSERT INTO day VALUES("2021.06.15");
INSERT INTO day VALUES("2021.06.16");
INSERT INTO day VALUES("2021.06.17");
INSERT INTO day VALUES("2021.06.18");
INSERT INTO day VALUES("2021.06.19");
--
INSERT INTO cabinet VALUES("Актовый зал","акт");
INSERT INTO cabinet VALUES("Учительская","уч.");
INSERT INTO cabinet VALUES("Улица","ул.");
INSERT INTO cabinet VALUES("Кабинет технологии Мальчиков","тех");
INSERT INTO cabinet VALUES("Спортивный зал","с/з");
INSERT INTO cabinet VALUES("Кабинет № 1","к.1");
INSERT INTO cabinet VALUES("Кабинет № 2","к.2");
INSERT INTO cabinet VALUES("Кабинет № 3","к.3");
INSERT INTO cabinet VALUES("Кабинет № 4","к.4");
INSERT INTO cabinet VALUES("Кабинет № 5","к.5");
INSERT INTO cabinet VALUES("Кабинет № 6","к.6");
INSERT INTO cabinet VALUES("Кабинет № 7","к.7");
INSERT INTO cabinet VALUES("Кабинет № 8","к.8");
INSERT INTO cabinet VALUES("Кабинет № 9","к.9");
INSERT INTO cabinet VALUES("Кабинет № 10","к.10");
INSERT INTO cabinet VALUES("Кабинет № 11","к.11");
INSERT INTO cabinet VALUES("Кабинет № 12","к.12");
INSERT INTO cabinet VALUES("Кабинет № 13","к.13");
INSERT INTO cabinet VALUES("Кабинет № 14","к.14");
INSERT INTO cabinet VALUES("Кабинет № 15","к.15");
INSERT INTO cabinet VALUES("Кабинет № 16","к.16");
INSERT INTO cabinet VALUES("Кабинет № 17","к.17");
INSERT INTO cabinet VALUES("Кабинет № 18","к.18");
INSERT INTO cabinet VALUES("Кабинет № 19","к.19");
INSERT INTO cabinet VALUES("Кабинет № 20","к.20");
INSERT INTO cabinet VALUES("Кабинет № 21","к.21");
INSERT INTO cabinet VALUES("Кабинет № 22","к.22");
INSERT INTO cabinet VALUES("Кабинет № 23","к.23");
INSERT INTO cabinet VALUES("Кабинет № 24","к.24");
INSERT INTO cabinet VALUES("Кабинет № 25","к.25");
INSERT INTO cabinet VALUES("Кабинет № 26","к.26");
INSERT INTO cabinet VALUES("Кабинет № 27","каб.27");
--
INSERT INTO weekday VALUES("Воскресенье","вс",0);
INSERT INTO weekday VALUES("Понедельник","пн",1);
INSERT INTO weekday VALUES("Вторник","вт",2);
INSERT INTO weekday VALUES("Среда","ср",3);
INSERT INTO weekday VALUES("Четверг","чт",4);
INSERT INTO weekday VALUES("Пятница","пт",5);
INSERT INTO weekday VALUES("Суббота","cб",6);
--
INSERT INTO subject VALUES("Физкультура","Физ-ра");
INSERT INTO subject VALUES("Литература","Литература");
INSERT INTO subject VALUES("Технология","Технология");
INSERT INTO subject VALUES("Русский язык","Рус.яз.");
INSERT INTO subject VALUES("Математика","");
INSERT INTO subject VALUES("ИЗО","");
INSERT INTO subject VALUES("Музыка","");
INSERT INTO subject VALUES("Немецкий язык","");
INSERT INTO subject VALUES("Английский язык","");
INSERT INTO subject VALUES("Биология","");
INSERT INTO subject VALUES("Химия","");
INSERT INTO subject VALUES("Физика","");
INSERT INTO subject VALUES("География","");
INSERT INTO subject VALUES("ОБЖ","");
INSERT INTO subject VALUES("История","");
INSERT INTO subject VALUES("Астрономия","");
INSERT INTO subject VALUES("Обществознание","");
INSERT INTO subject VALUES("Экономика","");
INSERT INTO subject VALUES("Право","");
INSERT INTO subject VALUES("-","");
INSERT INTO subject VALUES("Классный час","");
--
INSERT INTO interval VALUES(0,"08:30","09:15");
INSERT INTO interval VALUES(1,"09:30","10:20");
INSERT INTO interval VALUES(2,"10:30","11:20");
INSERT INTO interval VALUES(3,"11:30","12:20");
--
INSERT INTO class VALUES("1 A","");
INSERT INTO class VALUES("1 Б","");
INSERT INTO class VALUES("1 В","");
INSERT INTO class VALUES("2 А","");
INSERT INTO class VALUES("2 Б","");
INSERT INTO class VALUES("2 В","");
INSERT INTO class VALUES("3 А","");
INSERT INTO class VALUES("3 Б","");
INSERT INTO class VALUES("3 В","");
INSERT INTO class VALUES("4 А","");
INSERT INTO class VALUES("4 Б","");
INSERT INTO class VALUES("4 В","");
INSERT INTO class VALUES("5 А","");
INSERT INTO class VALUES("5 Б","");
INSERT INTO class VALUES("5 В","");
INSERT INTO class VALUES("6 А","");
INSERT INTO class VALUES("6 Б","");
INSERT INTO class VALUES("6 В","");
INSERT INTO class VALUES("7 А","");
INSERT INTO class VALUES("7 Б","");
INSERT INTO class VALUES("7 В","");
INSERT INTO class VALUES("8 А","");
INSERT INTO class VALUES("8 Б","");
INSERT INTO class VALUES("8 В","");
INSERT INTO class VALUES("9 А","");
INSERT INTO class VALUES("9 Б","");
INSERT INTO class VALUES("9 В","");
INSERT INTO class VALUES("10 Технологический профиль","");
INSERT INTO class VALUES("10 Универсальный профиль","");
INSERT INTO class VALUES("11 Технический профиль","");
INSERT INTO class VALUES("11 Универсальный профиль","");
INSERT INTO class VALUES("Подготовительная группа","");
--
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
INSERT INTO teacher VALUES("","");
